# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='date_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='date_to',
            field=models.DateField(),
        ),
    ]
